version: '3'

networks:
  app-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./replica
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://backend:3000
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/certbot/:ro
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./serverside
      dockerfile: Dockerfile
    expose:
      - "3000"
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
